version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    expose:
      - 3000
    environment:
      DATABASE_URL: "mysql://admin:password@localhost:3306/db"
      AUTH_SECRET: development
      PORT: 3000
  db:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
    expose:
      - 3306
volumes:
  database:
